### ISSUE TITLE
Interval is ignored when scheduling transactions

### ISSUE THREAD

**Issue by ibnzbssrckr** [scarpent/ledgerbil#1]
I have tried this exact schedule phrase from the documentation and ones similar and it is always just scheduled for every week:

2018/02/17 chop chop hair                                     
    ;; schedule ; weekly ; every 6 weeks
    e: misc: haircuts
    l: credit card: mega                    $-18

**Comment by scarpent** [comment]
Oh! Sorry about that, that's a mistake. It should be:

```
;; schedule ; weekly ;; every 6 weeks
```
We need an empty spot `;;` where for monthly we can specify days of the month. (In the future it would be nice to be able to use that spot for specifying days of the week, but that's not done yet.)

I've pushed an update to fix the readme. Thank you for trying out ledgerbil and reporting this!

**Comment by ibnzbssrckr** [comment]
Thanks. That does fix it.
