### ISSUE TITLE
Feature request: Daily scheduling

### ISSUE THREAD

**Issue by ibnzbssrckr** [scarpent/ledgerbil#2]
I would love to have the ability to schedule a transaction every X number of days. I would suspect this would be done with the addition of a 'daily' keyword. I will look over the code but it is in all likelihood above my abilities.

**Comment by scarpent** [comment]
Can you tell me more about an example scenario for this? What kind of transaction might occur every X days?

**Comment by ibnzbssrckr** [comment]
The primary reason is I have three bills that occur every 30 days.

**Comment by scarpent** [comment]
Interesting billing interval. I'll think on it a bit -- might not be that hard to add.

**Comment by scarpent** [comment]
Okay! Seems like an odd interval to me but easy enough to add and happy to be able to do it for you, sir. I've pushed the change. Thanks again for trying out ledgerbil -- it's great to have someone using it!

**Comment by ibnzbssrckr** [comment]
That's incredible! Thanks! BTW I don't think I am the only one using it as I found out about your project on the ledger-cli message board.
